### ISSUE TITLE
Flesh out match key documentation

### ISSUE THREAD

**Issue by leibovic** [mozilla-services/switchboard-experiments#15]

**Comment by milescrabill** [comment]
I tried to give a little more detail in https://github.com/mozilla-services/switchboard-experiments/commit/db4be835c739e1f59a47de27d5264257e22d6ffb. Does that seem like enough?

**Comment by leibovic** [comment]
Thanks, I think that helps. We could also update the sample config.

**Comment by leibovic** [comment]
Also, I'd like to see more documentation about the keys that are currently supported.

**Comment by milescrabill** [comment]
To clarify, any key/value pair in the experiments file is effectively supported, so it should in effect be self-documenting. Do you want a table or something of currently used keys?

There is an updated example experiments file here: https://github.com/mozilla-services/switchboard-server/blob/master/experiments/example_regexp_experiments.json.

**Comment by leibovic** [comment]
I'd also like a list of all of the supported keys. Right now the documentation only mentions `appId`, but I assume there are more that are supported.

**Comment by milescrabill** [comment]
The keys are whatever are specified in the experiments file. Nothing is
hard coded, so you can make up whatever you want! They just have to be
key/value pairs in the match object. (where the value is a regexp)

**Comment by leibovic** [comment]
I don't think you understand what I'm saying... you couldn't just say something like "user": "margaret leibovic", since support for that wouldn't exist on the server. I'm asking which keys, e.g. "appId", "locale" (I assume that exists?), etc. are supported.

**Comment by leibovic** [comment]
After talking with @milescrabill on Vidyo, I now realize that the keys all come from the client, so I'll update the documentation to reflect that, and specify what's supported.
