### ISSUE TITLE
Why are buckets.min and buckets.max string containing integer and not integer?

### ISSUE THREAD

**Issue by Natim** [mozilla-services/switchboard-experiments#49]

**Comment by leibovic** [comment]
@milescrabill Do you have an answer? I think I've just gone along with whatever convention already existed.

**Comment by Natim** [comment]
I've seen that in the file there is one that is not using string but integer.
It was easier for me to validate that an integer is between 0 and 100 but I can do it with a regexp as well.

**Comment by milescrabill** [comment]
This is up to convention, if it's working on your end I think the key is to be consistent. Since the other values are in quotes, I think quoting everything makes sense.

**Comment by Natim** [comment]
Ok I have created #51 to address this.
